### ISSUE TITLE
What is .NET Ore?

### ISSUE THREAD

**Issue by christophwille** [campusMVP/dotnetCoreLogoPack#4]
Just wanted to point out that you should show the logo around to non-MS Devs and ask them to read it out aloud. The C & O won't be discernible.

**Comment by jmalarcon** [comment]
We'll, I think it's pretty understandable even outside our "bubble", and that the "o" inside the "C" is evident and a good way to transmit the "Core" idea.

Obviously the logo doesn't have to appeal to everyone, but design-wise is pretty clever IMHO.

Since it's not an official one, you don't have to use it if you don't want or think is not clear enough. But is clearer than no logo at all!
